### PR TITLE
reduce ReadSimVars() count to improve performance

### PR DESCRIPTION
**Pull request by cpuwolf**
proposal of issue #9 , This has been tested on device with PilotEdge.net ATC
https://x-plane.vip/quickmade/qg1k/

1. use std::list instead of std::vector, for circular iteration
2. list max 5 SimVars reading in every frame
3. VimVars clean() needs update list iterator

### CODE REVIEW

**Comment by cpuwolf** [comment]
[MobiFlightWasmModule.zip](https://github.com/MobiFlight/MobiFlight-WASM-Module/files/8615115/MobiFlightWasmModule.zip)
Engineering Build is attached

**Comment by DocMoebiuz** [comment]
Hi! Very interesting idea. I would like to make the number of vars read at once configurable.

I think by default it should behave the way it used to behave and reading all vars at once.

But with sending a message like MF.SimVars.SetVarLimit we could then limit it to a desired number.

**Comment by Koseng** [comment]
Hi, 
I also like the concept. In #9 I reported my tests.

I agree making it configurable is a good idea.

I disagree in not setting a limit. My tests show it suddenly starts and gets worse and worse with numbers of variables increasing. I think it is hard  for someone  to figure out that suddenly the number of variables leads to stutters.

- I would limit the number of read variables per frame to something like 30 per default. Then with 30 FPS you can update 900 variables each second or 200 variables each 222ms.
- I don't know whether the typical mobiflight user has more than 200 active variables?

@cpuwolf 
Any special reason to switch to a list and use an list iterator?
We could just stay with the vector and iterate an int index. Performance wise this should be better.

**Comment by cpuwolf** [comment]
@Koseng list iterator, because I am newbie of vector, I failed to iterate an int index. that would be great if you can come up with better solution. I agree, the limitation can be configurable

**Comment by DocMoebiuz** [comment]
@cpuwolf - Thanks for the preparation of this. Please take a look at: https://github.com/MobiFlight/MobiFlight-WASM-Module/pull/13 - I made some changes and additions, it would be great if you could test it too.

I will close this PR.

**Pull request closed without merging**
