### PR TITLE
Multiclient capability for SimVars

### LINKED ISSUE #4: Wasm Module not multi client ready for LVar access
Several applications now use the Mobiflight-WASM to access L-Vars and A-Vars. If they would run at the same time, it would lead to issues, since the LVar access is not made for a mulit client scenario.

Multi client access for LVars via the mobiflight wasm module is needed.

### PR DESCRIPTION
**Pull request by Koseng**
Fixes #4 

Hi, several applications now use the Mobiflight-WASM to access L-Vars and A-Vars. If they would run at the same time, it would lead to issues, since the LVar access is not made for a mulit client scenario.

This PR adds multi client access. A new client can register via the existing command interface and new client-data-areas are created by the wasm module. The client gets informed about the new data-areas via the existing response interface. After that initial step the new client uses its private client-data-areas.
 
It should be compatible, with no changes on the Mobiflight Client needed. 

I tested with Python clients https://github.com/Koseng/MSFSPythonSimConnectMobiFlightExtension. Prototype using the extended wasm is here: https://github.com/Koseng/MSFSPythonSimConnectMobiFlightExtension/tree/main/prototype

conceptMultiClient

### CODE REVIEW

**Comment by Koseng** [comment]
**Short description of implementation, to ease the review:**

A new struct “Client” is introduced which represents the connection of a particular client. That struct contains the unique name, id,  client data area ids and list of simvars for that client. The WASM module contains a new variable “RegisteredClients” which is a list of current known and registered clients.

On module init of the WASM module, the default MobiFlight client is auto registered as the first client. Through the command “MF.Clients.Add.MyName” other clients can be created and registered later on. If a new client registers, it is informed about its assigned client data areas via a short json in the response channel. 

When a new client is registered and  the subscriptions to client data areas are created, the unique client id is used as RequestID in the subscriptions.  In the dispatch callback on client data change, the RequestID is subsequently used to identify the respective client and its corresponding client data areas.

In case a client crashes or needs to reconnect and sends again the command “MF.Clients.Add.MyName”, it is checked whether a client “MyName” already is registered and the existing information is returned.

**Comment by MobiFlight-Admin** [comment]
@Koseng Nice job, great idea! Question: Is this 100% backward compatible with the MobiFlight Connector side? Have you tested that part?

**Comment by Koseng** [comment]
@MobiFlight-Admin I tested as much as I can, but since I am not running a real mobiflight board I cannot be 100% sure. I think it would be a good idea, if you would run that wasm module for a bit. I attached the debug version which represents the PR.

If it is ok, I could also add a description to the readme.md on how to use the wasm module from other clients.
[StandaloneModule.zip](https://github.com/MobiFlight/MobiFlight-WASM-Module/files/7739658/StandaloneModule.zip)

**Review by DocMoebiuz — APPROVED** [review]
THANK YOU!!!

**Pull request merged**
